#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine
# Install nginx on your web-01 server

sudo apt-get update -y
sudo apt-get install -y nginx
sudo service nginx start
echo 'Hello World!'| sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
sudo service nginx reload
