#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page 
# that contains the string Ceci n'est pas une page
sudo apt-get update -y
sudo apt-get install -y nginx
sudo service nginx start
sudo chmod 777 /var/www/html/index.nginx-debian.html
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" >> /var/www/html/notfoundpage404.html
sudo sed -i '/listen 80 default_server;/a error_page 404 /notfoundpage404.html;' /etc/nginx/sites-enabled/default
sudo service nginx restart
