#!/usr/bin/env bash
# script that configures an Ubuntu server

sudo cp /etc/hosts ~/hosts.copy
sudo sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.copy
sudo cp -f ~/hosts.copy /etc/hosts
